version: 2.1

jobs: 
  build:
    docker:
      - image: cimg/node:18.17.1
      steps:
        - checkout
        - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build

  deploy:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - run: echo "Deploying..."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
